### ISSUE TITLE
Add TitleCase option

### ISSUE THREAD

**Issue by kontur** [kontur/typeface-strings#9]
In addition to -uc and -lc

**Comment by tderkert** [comment]
I forked your repo a while ago and added this feature. Feel free to pull it if it looks ok.
https://github.com/tderkert/typeface-strings/commit/ca86c51d5c8db682f45c8fc9437da64e475974db

**Comment by kontur** [comment]
Perfect, thanks for the PR! Added you also to the newly added contributors list ;)

**Comment by tderkert** [comment]
Great! Glad I could contribute, even if just a little bit!

**Comment by tderkert** [comment]
Worth noting is that `dist/typestrings` was left untouched.

**Comment by kontur** [comment]
Cheers for the help, I compiled the updated binary and bumped the version ;)
